version: "3.6"
services:
  db:
    image: mariadb
    container_name: "mdb"
    restart: always
    environment: 
      - MYSQL_ROOT_PASSWORD=root@1234
      - MYSQL_ALLOW_EMPTY_PASSWORD
      - MYSQL_USER= agsroot
      - MYSQL_PASSWORD= ags
    ports:
      - "9906:3306"
    volumes:
    - ./data:/var/lib/mysql
    command: mysqld --innodb-flush-method=O_DSYNC

  p3app:
    build: .
    container_name: "nodejs"
    image: p3app:latest
    ports:
    - "80:3000"
    links:
    - "db"
    volumes:
    - .:/usr/src/app